[package]
name = "ratisui"
version = "0.1.0"
edition = "2021"
authors = ["honhimw <honhimw@outlook.com>"]
rust-version = "1.80.1"
build = "build.rs"

[dependencies]
anyhow = "1"
log = "0.4"

ratatui = { version = "0.28.1" }
tui-textarea = { version = "0.6.1", features = ["crossterm"]}
throbber-widgets-tui = "0.7"
tui-tree-widget = "0.22.0"
tui-logger = "0.13"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
crossbeam-channel = "0.5"

rustls = { version = "0.23.12", default-features = false, features = ["ring", "std"] }
redis = { version = "0.26", features = [
    "tokio-comp",
    "tokio-rustls-comp",
    "cluster-async",

] }
deadpool-redis = { version = "0.17", features = ["serde", "cluster"] }

strum = "0.26.3"
uuid = { version = "1.10.0", features = ["v4"] }
toml = "0.8.19"
dirs = "5.0.1"
base64 = "0.22.1"
clap = "4.5.16"
tokio = { version = "1.39.3", features = ["full"] }
encoding_rs = "0.8.34"
chronoutil = "0.2.7"
itertools = "0.13.0"
unicode-width = "0.1.13"
once_cell = "1"

tree-sitter = "0.23"
tree-sitter-highlight = "0.23"
tree-sitter-json = "0.23"
tree-sitter-html = "0.23"

# git crates
[build-dependencies]
cc="*"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
strip = "debuginfo"