[package]
name = "ratisui"
version = "0.1.0"
edition = "2021"
authors = ["honhimw <honhimw@outlook.com>"]
rust-version = "1.80.1"
build = "build.rs"

[dependencies]
anyhow = "1.0"
log = "0.4"
ratatui = "0.28.0"
#ratatui = { version = "0.28", default-features = false, features = [
#    'crossterm',
#    'serde',
#] }

tui-textarea = "0.6.1"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"
crossbeam-channel = "0.5"

rustls = { version = "0.23.12", default-features = false, features = ["ring", "std"] }
redis = { version = "0.26.1", features = [
    #    "tls-rustls",
    #    "cluster",
    "json",
    "connection-manager",
    "tokio-comp",
    "tokio-rustls-comp",
    "cluster-async",
    "serde_json"
] }
strum = "0.26.3"
throbber-widgets-tui = "0.6.0"
tui-widgets = "0.3.0"
tui-tree-widget = "0.22.0"
uuid = { version = "1.10.0", features = ["v4"] }
toml = "0.8.19"
dirs = "5.0.1"
aes-gcm = "0.10.3"
base64 = "0.22.1"
aead = { version = "0.5.2", features = ["std"] }
tree-sitter = "0.22.6"
tree-sitter-json = "0.21.0"
tree-sitter-highlight = "0.22.6"
clap = "4.5.16"
once_cell = "1.19.0"
tokio = { version = "1.39.3", features = ["full"] }
async-trait = "0.1.81"
hex = "0.4.3"
encoding_rs = "0.8.34"
log4rs = "1.3.0"
chronoutil = "0.2.7"
deadpool-redis = { version = "0.16.0", features = ["serde", "cluster"] }
#syntect = "5.2.0"

# git crates

[build-dependencies]
cc="*"