[package]
name = "ratisui"
version = "0.1.2"
edition = "2021"
authors = ["honhimw <honhimw@outlook.com>"]
rust-version = "1.81.0"
build = "build.rs"

[workspace]
members = ["ratisui-deadpool-redis", "ratisui-jaded", "ratisui-tree-sitter-ron"]

[workspace.dependencies]
log = "0.4"
redis = "0.27"
serde = "1"
tokio = "1"
tree-sitter = "0.24"

[dependencies]
anyhow = "1"
log = { workspace = true }

ratatui = { version = "0.28.1", features = [
    "unstable-rendered-line-info",
    "macros",
] }
ratatui-macros = "0.5.0"
tui-textarea = { version = "0.6.1", features = ["crossterm"] }
throbber-widgets-tui = "0.7"
tui-tree-widget = "0.22.0"
tui-logger = "0.13"

serde = { workspace = true, features = ["derive"] }
serde_json = "1"
crossbeam-channel = "0.5"

rustls = { version = "0.23.12", default-features = false, features = ["ring", "std"] }
redis = { workspace = true, features = [
    "tokio-comp",
    "tokio-rustls-comp",
    "cluster-async",
] }
deadpool-redis = { path = "ratisui-deadpool-redis", features = [
    "serde",
    "cluster",
    "log",
] }

strum = "0.26.3"
uuid = { version = "1.10.0", features = ["v4"] }
#toml = { version = "0.8.19"}
ron = { version = "0.8.1", features = ["default"] }
dirs = "5.0.1"
base64 = "0.22.1"
clap = "4.5.16"
tokio = { workspace = true, features = ["full"] }
encoding_rs = "0.8.34"
chronoutil = "0.2.7"
itertools = "0.13.0"
unicode-width = "0.2.0"
once_cell = "1"
futures = "0.3.30"

jaded = { path = "ratisui-jaded", features = ["serde"] }
protobuf = { version = "3.5.1" }

tree-sitter = { workspace = true}
tree-sitter-highlight = "0.24"
tree-sitter-json = "0.24"
tree-sitter-html = "0.24"
tree-sitter-ron = { path = "ratisui-tree-sitter-ron" }

# git crates

[build-dependencies]
cc = "*"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
strip = "debuginfo"
