name: Build Aarch64

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: rust-toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-gnu
    - name: Cargo
      uses: actions-rs/cargo@v1
      with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-gnu --release
    - name: Archive
      run: tar -czvf ./target/aarch64-unknown-linux-gnu/release/ratisui-linux-aarch64.tar.gz LICENSE README.md -C ./target/aarch64-unknown-linux-gnu/release ratisui
    - name: Print Dir
      run: ls -lah ./target/aarch64-unknown-linux-gnu/release
    # - name: Add aarch64 target
    #   run: rustup target add aarch64-unknown-linux-gnu
    # - name: Build aarch64
    #   run: cargo build --target aarch64-unknown-linux-gnu
          
