name: Build Aarch64

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  build:
    runs-on: ${{ matrix.os }}
    needs: create_release
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Aarch64 toolchain
      run: apt-get install -y gcc-aarch64-linux-gnu
    - name: Add aarch64 target
      run: rustup target add aarch64-unknown-linux-gnu
    - name: Build aarch64
      run: cargo build --target aarch64-unknown-linux-gnu
    
