name: Build Aarch64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        target: aarch64-unknown-linux-gnu
    # - name: Aarch64 toolchain
    #   run: sudo apt-get install -y gcc-aarch64-linux-gnu
    # - name: Add aarch64 target
    #   run: rustup target add aarch64-unknown-linux-gnu
    - name: Build aarch64
      run: cargo build --target aarch64-unknown-linux-gnu
          
