name: Build MacOS

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-13 ]
        rust: [ stable ]

    steps:
      - name: Checkout
        uses: actions/Checkout@v4
      - name: Echo OS Info
        run: uname -a
      - name: Cargo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release
      - name: Verify
        run: |
          ./target/release/ratisui --version
          ./target/release/ratisui --help
      - name: Create Meta File
        run: |
          echo "License         : MIT" > META-INF
          echo "Repository URL  : https://github.com/${GITHUB_REPOSITORY}" >> META-INF
          echo "Commit SHA      : ${{ github.sha }}" >> META-INF
          echo "Build At        : $(date)" >> META-INF
      - name: Create Temp Dir
        run: |
          mkdir artifacts
          mv ./target/release/ratisui ./artifacts
          mv META-INF ./artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ratisui
          compression-level: 9
          retention-days: 1
          path: ./artifacts/*
